container:
  image: cirrusci/flutter:latest
osx_instance:
  image: mojave-xcode-10.2
build_task:
  binaries_artifacts:
    path: "build/*"
  build_script:
    - flutter packages get
    - cd ios && pod install
    - flutter build ios --no-codesign --release
test_task:
  pub_cache:
    folder: ~/.pub-cache