osx_instance:
  image: mojave-xcode-10.2
build_task:
  build_script:
    - wget https://storage.googleapis.com/flutter_infra/releases/stable/macos/flutter_macos_v1.9.1+hotfix.2-stable.zip
    - unzip flutter_macos_v1.9.1+hotfix.2-stable.zip
    - export PATH="$PATH:`pwd`/flutter/bin"
    - flutter packages get
    - cd ios && pod install
    - flutter build ios --no-codesign --release
  binaries_artifacts:
    path: "build/*"